 # This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches: [ main ]
    
    
  push:
    branches: [ main ]
    
  pull_request_review:
    types:
      - submitted
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     environment: notification
#     env:
#      SECRET_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: test
        run: echo ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Push action
        if: ${{ github.event_type  == 'push' }}
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: 'POST'
          data: '{"name":"${{ github.event.pull_request.user.login }}", "message":"created a new PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}'

      - name: check for new PR
        if: ${{ github.event.action == 'opened' }}
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: 'POST'
          data: '{"name":"${{ github.event.pull_request.user.login }}", "message":"created a new PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}'

      - name: Check for new PR revision
        if: ${{ github.event.action == 'synchronize' }}
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: 'POST'
          data: '{"name":"${{ github.event.pull_request.user.login }}", "message":"pushed a new revision \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}'

      - name: Check for merge
        if: github.event.pull_request.merged == true
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: 'POST'
          data: '{"name":"${{ github.actor }}", "message":"merged a PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}'

      - name: PR approved
        if: github.event.review.state == 'approved'
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          method: 'POST'
          data: '{"name":"${{ github.actor }}", "message":"approved a PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}'
