 # This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches: [ main ]
    
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: notifications
    env:
     URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - shell: bash
        if: ${{ github.event.action == 'opened' }}
        run: curl -H "Content-Type:application/json" -X POST -d '{"name":"${{ github.event.pull_request.user.login }}", "message":"created a new PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}' "$URL"

#         run: |
#          echo ${{ secrets.SLACK_WEBHOOK_URL }} | sed 's/./& /g' 
#          echo "$SUPER_SECRET" 
#          curl -H "Content-Type:application/json" -X POST -d '{"name":"${{ github.event.pull_request.user.login }}", "message":"created a new PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}' "$SUPER_SECRET"        

        
      # Runs a single command using the runners shell
      - name: Check for new PR
        if: ${{ github.event.action == 'opened' }}
        env:
         SUPER_SECRET: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: curl -H "Content-Type:application/json" -X POST -d '{"name":"${{ github.event.pull_request.user.login }}", "message":"created a new PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}' "$SUPER_SECRET"  

#       - name: check for new PR
#         if: ${{ github.event.action == 'opened' }}
#         uses: fjogeleit/http-request-action@v1.8.1
#         with:
#           url: 'https://hooks.slack.com/workflows/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'
#           method: 'POST'
#           data: ' {"name":"${{ github.event.pull_request.user.login }}", "message":"created a new PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}'

      - name: Check for new PR revision
        if: ${{ github.event.action == 'synchronize' }}
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: 'https://hooks.slack.com/workflows/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'
          method: 'POST'
          data: ' {"name":"${{ github.event.pull_request.user.login }}", "message":"pushed a new revision \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}'

      - name: Check for merge
        if: github.event.pull_request.merged == true
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: 'https://hooks.slack.com/workflows/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'
          method: 'POST'
          data: ' {"name":"${{ github.actor }}", "message":"merged a PR \n ${{ github.base_ref }}  |  ${{ github.event.pull_request.title }}", "pr":"${{ github.event.pull_request.html_url }}"}'
